import turtle
t=turtle.Turtle()
s=turtle.Screen()
s.setup(850,800)
s.bgcolor('black')
t.color('violet')
t.begin_fill()
t.penup()
t.left(110)
t.fd(50)
t.pendown()
t.speed(0)
t.circle(30)
t.penup()
t.backward(150)
t.pendown()
t.fd(25)
t.end_fill()

t.penup()
t.goto(-140,85)
t.pendown()
t.color('yellow')
t.write("HAPPY",align="center",font=("arial",49,"bold"))
t.penup()
t.goto(-110,-10)
t.pendown()
t.color('lightblue')
t.write("J",align="center",font=("arial",59,"bold"))
t.penup()
t.goto(-10,-10)
t.pendown()
t.color('lightblue')
t.write("HN'S",font=("arial",49,"bold"))
t.penup()
t.goto(65,-111)
t.pendown()
t.color('red')
t.write("DAY",font=("arial",49,"bold"))
t.penup()
t.goto(-205,-120)
t.pendown()
t.color("yellow","tomato")
t.begin_fill()
for i in range(60):
    t.fd(100)
    t.lt(165)
t.end_fill()
t.penup()
t.goto(-185,5)
t.pendown()
t.color("red","green")
t.begin_fill()
for i in range(60):
    t.fd(85)
    t.lt(165)
t.end_fill()

t.penup()
t.goto(-310,29)
t.pendown()
t.color("blue","magenta")
t.begin_fill()
for i in range(60):
    t.fd(70)
    t.lt(165)
t.end_fill()
t.penup()
t.goto(-300,120)
t.pendown()
t.color("yellow","cyan")
t.begin_fill()
for i in range(60):
    t.fd(55)
    t.lt(165)
t.end_fill()
t.color('cyan')
t.penup()
t.goto(75,-170)
t.pendown()
t.write("Thinking Of you,",font=("italic",19))
t.penup()
t.goto(75,-230)
t.pendown()
t.write("And Hoping You,",font=("arial",19))
t.penup()
t.goto(75,-260)
t.pendown()
t.write("Have a beautiful day,",font=("arial",19))
t.penup()
t.goto(75,-290)
t.pendown()
t.write("From All Of The",font=("arial",19))
t.penup()
t.goto(75,-330)
t.pendown()
t.color('yellow')
t.write("World!!!!!",font=("arial",21))
t.width(10)
t.penup()
t.fd(200)
t.lt(69)
t.fd(470)

t.pendown()
t.color("blue","maroon")
t.begin_fill()
t.rt(90)
t.circle(55)
t.lt(180)
t.circle(90)
t.end_fill()
t.color('maroon')
t.begin_fill()
t.lt(90)
t.fd(70)
t.rt(150)
t.fd(20)
t.lt(90)
t.fd(50)
t.end_fill()
t.color('gold')
t.write("2023",font=("verdana",24,"bold"))
t.hideturtle()
turtle.exitonclick()
